---

- name: install base packages
  apt:
    name: "{{ rundeck_base_packages }}"
    state: present

# https://docs.rundeck.com/docs/learning/howto/migrate-to-rundeck-packages-repo.html
- name: add apt key
  ansible.builtin.apt_key:
    url: https://packages.rundeck.com/pagerduty/rundeck/gpgkey
    state: present

- name: creating apt config file rundeck repo
  copy:
    content:  |
              deb https://packages.rundeck.com/pagerduty/rundeck/any/ any main
              deb-src https://packages.rundeck.com/pagerduty/rundeck/any/ any main
    dest: /etc/apt/sources.list.d/rundeck.list

- name: apt update cache
  apt:
    update_cache: yes

- name: install rundeck
  apt:
    name: "{{ rundeck_packages }}"
    state: present

- name: install nginx
  apt:
    name: "{{ nginx_packages }}"
    state: present
