---

- name: set OS dependent variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_facts.os_family }}.yaml'

- name: set OS dependent tasks
  include_tasks: '{{ item }}'
  with_first_found:
    - '{{ ansible_facts.os_family }}.yaml'

- name: rundeck config
  include_tasks: rundeck_config.yml

- name: nginx config
  include_tasks: nginx_config.yml
