---

- name: configure framework.properties
  template:
    src: framework.properties.j2
    dest: /etc/rundeck/framework.properties
  notify: restart rundeckd
  tags: rundeck_config

- name: configure rundeck-config.properties
  template:
    src: rundeck-config.properties.j2
    dest: /etc/rundeck/rundeck-config.properties
  notify: restart rundeckd
  tags: rundeck_config

- name: configure variables
  template:
    src: rundeck_profile.j2
    dest: "{{ rundeck_override_variables }}"
  notify: restart rundeckd
  tags: rundeck_config

- name: configure jaas-activedirectory
  template:
    src: jaas-activedirectory.j2
    dest: "{{ rundeck_profile_ad.JAAS_CONF }}"
    owner: rundeck
    group: rundeck
  notify: restart rundeckd
  when: rundeck_active_directory_enable
  tags: rundeck_config
