---

- name: restarting rundeck
  systemd:
    name: rundeckd
    state: restarted
    enabled: yes
  listen: restart rundeckd

- name: check if rundeck is running
  uri: 
    url: http://{{ rundeck_addr }}:{{ rundeck_port }}
    validate_certs: no
  register: rundeck_running
  until: rundeck_running.status == 200
  retries: 10
  delay: 20
  listen: restart rundeckd

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
